[[databases]]
name = "Test database 1"
database = "devdb"
type = "postgresql"
username = "devuser"
password = "changeme"
port = 5432
host = "localhost"
generated_id = "16678159-ff7e-4c97-8c83-0adeff214681"

[[databases]]
name = "Test database 2"
database = "devdb"
type = "postgresql"
username = "devuser"
password = "changeme"
port = 5432
host = "localhost"
generated_id = "16678156-ff7e-4c97-8c83-0adeff214681"

[[databases]]
name = "Test database 3"
database = "mariadb"
type = "mysql"
username = "mariadb"
password = "changeme"
port = 3306
host = "localhost"
generated_id = "16678124-ff7e-4c97-8c83-0adeff214681"
