[[databases]]
name = "Test database 1 - rust"
database = "devdb"
type = "postgresql"
username = "devuser"
password = "changeme"
port = 5432
host = "db"
generated_id = "16678159-ff7e-4c97-8c83-0adeff214689"

[[databases]]
name = "Test database 2 - rust"
database = "devdb"
type = "postgresql"
username = "devuser"
password = "changeme"
port = 5432
host = "db"
generated_id = "16678156-ff7e-4c97-8c83-0adeff214654"

[[databases]]
name = "Test database 3 - rust"
database = "mariadb"
type = "mysql"
username = "mariadb"
password = "changeme"
port = 3306
host = "db1"
generated_id = "16678124-ff7e-4c97-8c83-0adeff214667"
