#name: Docker Publish
#
#on:
#  workflow_call:
#    inputs:
#      image_name:
#        required: false
#        type: string
#        default: 'portabase/agent'
#      add_latest:
#        required: false
#        type: boolean
#        default: false
#      target:
#        required: false
#        type: string
#        default: 'prod'
#      dockerfile:
#        required: false
#        type: string
#        default: './docker/Dockerfile'
#    secrets:
#      DOCKER_USERNAME:
#        required: true
#      DOCKER_PASSWORD:
#        required: true
#
#jobs:
#  build-and-push:
#    runs-on: ubuntu-latest
#    permissions:
#      packages: write
#      contents: read
#    steps:
#      - name: Check out the repo
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#
#      - name: Set up QEMU (enables multi-arch emulation)
#        uses: docker/setup-qemu-action@v3
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Log in to Docker Hub
#        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Set tags
#        id: set-tags
#        run: |
#          REF_NAME=${GITHUB_REF#refs/tags/}
#          TAGS="${{ inputs.image_name }}:$REF_NAME"
#          if [[ "${{ inputs.add_latest }}" == "true" ]]; then
#            TAGS="$TAGS,${{ inputs.image_name }}:latest"
#          fi
#          echo "tags=$TAGS" >> $GITHUB_OUTPUT
#
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          file: ${{ inputs.dockerfile }}
#          platforms: linux/amd64,linux/arm64
#          push: true
#          tags: ${{ steps.set-tags.outputs.tags }}
#          target: ${{ inputs.target }}
#
#name: Docker Publish
#
#on:
#  workflow_call:
#    inputs:
#      image_name:
#        required: false
#        type: string
#        default: 'portabase/agent'
#      add_latest:
#        required: false
#        type: boolean
#        default: false
#      target:
#        required: false
#        type: string
#        default: 'prod'
#      dockerfile:
#        required: false
#        type: string
#        default: './docker/Dockerfile'
#    secrets:
#      DOCKER_USERNAME:
#        required: true
#      DOCKER_PASSWORD:
#        required: true
#
#jobs:
#  build-amd64:
#    name: Build AMD64 Image
#    runs-on: ubuntu-latest
#    outputs:
#      image: ${{ steps.set-job-output.outputs.image }}
#    steps:
#      - uses: actions/checkout@v4
#
#      - uses: docker/setup-buildx-action@v3
#
#      - uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Set AMD64 image tag
#        id: set-tags
#        run: |
#          REF_NAME=${GITHUB_REF#refs/tags/}
#          AMD64_IMAGE="${{ inputs.image_name }}:$REF_NAME-amd64"
#          echo "amd64_image=$AMD64_IMAGE" >> $GITHUB_OUTPUT
#
#      - name: Build and push AMD64
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          file: ${{ inputs.dockerfile }}
#          platforms: linux/amd64
#          push: true
#          tags: ${{ steps.set-tags.outputs.amd64_image }}
#          target: ${{ inputs.target }}
#
#  build-arm64:
#    name: Build ARM64 Image
#    runs-on: ubuntu-24.04-arm
#    outputs:
#      image: ${{ steps.set-job-output.outputs.image }}
#    steps:
#      - uses: actions/checkout@v4
#
#      - uses: docker/setup-buildx-action@v3
#
#      - uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Set ARM64 image tag
#        id: set-tags
#        run: |
#          REF_NAME=${GITHUB_REF#refs/tags/}
#          ARM64_IMAGE="${{ inputs.image_name }}:$REF_NAME-arm64"
#          echo "arm64_image=$ARM64_IMAGE" >> $GITHUB_OUTPUT
#
#      - name: Build and push ARM64
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          file: ${{ inputs.dockerfile }}
#          platforms: linux/arm64
#          push: true
#          tags: ${{ steps.set-tags.outputs.arm64_image }}
#          target: ${{ inputs.target }}
#
#
#  create-manifest:
#    name: Create Multi-Arch Manifest
#    runs-on: ubuntu-latest
#    needs:
#      - build-amd64
#      - build-arm64
#    steps:
#      - uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Create Docker manifest
#        run: |
#          REF_NAME=${GITHUB_REF#refs/tags/}
#
#          IMAGE="${{ inputs.image_name }}:$REF_NAME"
#          AMD64_IMAGE="$IMAGE-amd64"
#          ARM64_IMAGE="$IMAGE-arm64"
#
#          echo "AMD64_IMAGE=$AMD64_IMAGE"
#          echo "ARM64_IMAGE=$ARM64_IMAGE"
#
#          docker manifest create $IMAGE $AMD64_IMAGE $ARM64_IMAGE
#          docker manifest push $IMAGE
#
#          if [ "${{ inputs.add_latest }}" = "true" ]; then
#            docker manifest create ${{ inputs.image_name }}:latest $AMD64_IMAGE $ARM64_IMAGE
#            docker manifest push ${{ inputs.image_name }}:latest
#          fi

name: Docker Publish

on:
  workflow_call:
    inputs:
      image_name:
        required: false
        type: string
        default: 'portabase/agent'
      add_latest:
        required: false
        type: boolean
        default: false
      target:
        required: false
        type: string
        default: 'prod'
      dockerfile:
        required: false
        type: string
        default: './docker/Dockerfile'
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build:
    name: Build and push Docker images
    runs-on: ${{ matrix.platform == 'linux/amd64' && 'ubuntu-latest' || matrix.platform == 'linux/arm64' && 'ubuntu-24.04-arm' }}
    strategy:
      fail-fast: false
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tag
        id: set-tags
        run: |
          REF_NAME=${GITHUB_REF#refs/tags/}
          if [ "${{ matrix.platform }}" = "linux/amd64" ]; then
            IMAGE="${{ inputs.image_name }}:$REF_NAME-amd64"
          else
            IMAGE="${{ inputs.image_name }}:$REF_NAME-arm64"
          fi
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.set-tags.outputs.image }}
          target: ${{ inputs.target }}

      - name: Prepare artifact name
        id: artifact
        run: |
          platform=${{ matrix.platform }}
          echo "safe_platform=${platform//\//-}" >> $GITHUB_OUTPUT
          echo "${{ steps.set-tags.outputs.image }}" > image.txt

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: image-${{ steps.artifact.outputs.safe_platform }}
          path: image.txt
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false

  create-manifest:
    name: Create multi-arch Docker manifest
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131
        with:
          name: image-linux-amd64
          path: /tmp/digests/amd64

      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131
        with:
          name: image-linux-arm64
          path: /tmp/digests/arm64

      - name: Login to Docker
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

#      - name: Create and push manifest
#        run: |
#          AMD64_IMAGE=$(cat /tmp/digests/amd64/image.txt)
#          ARM64_IMAGE=$(cat /tmp/digests/arm64/image.txt)
#          REF_NAME=${GITHUB_REF#refs/tags/}
#          MANIFEST_IMAGE="${{ inputs.image_name }}:$REF_NAME"
#
#          docker manifest create $MANIFEST_IMAGE $AMD64_IMAGE $ARM64_IMAGE
#          docker manifest push $MANIFEST_IMAGE
#
#          if [ "${{ inputs.add_latest }}" = "true" ]; then
#            docker manifest create ${{ inputs.image_name }}:latest $AMD64_IMAGE $ARM64_IMAGE
#            docker manifest push ${{ inputs.image_name }}:latest
#          fi

      - name: Create and push manifest list
        working-directory: /tmp/digests
        run: |
          DOCKER_IMAGES="$(cat amd64/image.txt) $(cat arm64/image.txt)"
          REF_NAME=${GITHUB_REF#refs/tags/}
          MANIFEST_IMAGE="${{ inputs.image_name }}:$REF_NAME"

          docker buildx imagetools create $DOCKER_IMAGES -t $MANIFEST_IMAGE
          docker buildx imagetools inspect $MANIFEST_IMAGE

          if [ "${{ inputs.add_latest }}" = "true" ]; then
            docker buildx imagetools create $DOCKER_IMAGES -t ${{ inputs.image_name }}:latest
            docker buildx imagetools inspect ${{ inputs.image_name }}:latest
          fi